Change in configure to improve the Makefile, to handle PGI compiler and IBM compiler

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+bold=$(tput bold)
+reset=$(tput sgr0)
+
 usage="Usage:\n
 \t ./configure [-h|--help] [-i|--interactive] [-m|--with-mpi[=]<value>] [-H|--with-phdf5[=]<value>] [-c|--with-pnetcdf[=]<value>] [-a|--with-adios[=]<value>]\n
 \n
@@ -80,7 +83,7 @@ while getopts ":him:H:c:a:-:" opt; do
 	    esac;;
 	*)
             if [ "$OPTERR" = 1 ] || [ "${optspec:0:1}" != ":" ]; then
-                echo "Unknown option -${OPTARG}" >&2
+                echo "${bold}Unknown option${reset} -${OPTARG}" >&2
             fi
             ;;
     esac
@@ -88,25 +91,31 @@ done
 
 # Retrieve libraries path and set variables for the Makefile
 POSIX=1; POTOK=1; PNCDF=0; PHDF5=0; ADIOS=0; MPIIO=1
-echo "     Running configure script for BRIO benchmark"
+echo "     ${bold}Running configure script for BRIO benchmark${reset}"
 echo " "
 echo "Preparing compilation with: "
-if [ -z $MPI ]; then
-    MPIDIR=$(which mpif90)
-    if [ -z $MPIDIR ]; then
-	echo "ERROR: MPI not found; exiting..."
-	exit 1
+BGCOMPILER=$(which mpixlf90_r)
+if [ -z $BGCOMPILER ]; then
+    if [ -z $MPI ]; then
+	MPIDIR=$(which mpif90)
+	if [ -z $MPIDIR ]; then
+	    echo "${bold}ERROR${reset}: MPI not found; exiting..."
+	    exit 1
+	else
+	    MPIDIR=${MPIDIR%/*/*}
+	fi
     else
-	MPIDIR=${MPIDIR%/*/*}
+	MPIDIR=$MPI
     fi
+    echo "> ${bold}MPI library located at${reset}: "$MPIDIR
 else
-    MPIDIR=$MPI
+    echo "> ${bold}IBM MPI library${reset}"
+    MPIDIR=
 fi
-echo "> MPI library located at: "$MPIDIR
 if [ -z $HDF ]; then
     HDFDIR=$(which h5dump)
     if [ -z $HDFDIR ]; then
-	echo "> without parallel HDF5 library"
+	echo "> ${bold}without parallel HDF5 library${reset}"
     else
 	HDFDIR=${HDFDIR%/*/*}
 	PHDF5=1
@@ -116,12 +125,12 @@ else
     PHDF5=1
 fi
 if [ $PHDF5 -eq 1 ]; then
-    echo "> parallel HDF5 library located at: "$HDFDIR
+    echo "> ${bold}parallel HDF5 library located at${reset}: "$HDFDIR
 fi
 if [ -z $CDF ]; then
     CDFDIR=$(which ncmpidump)
     if [ -z $CDFDIR ]; then
-	echo "> without parallel NetCDF library"
+	echo "> ${bold}without parallel NetCDF library${reset}"
     else
 	CDFDIR=${CDFDIR%/*/*}
 	PNCDF=1
@@ -131,12 +140,12 @@ else
     PNCDF=1
 fi
 if [ $PNCDF -eq 1 ]; then
-    echo "> parallel NetCDF library located at: "$CDFDIR
+    echo "> ${bold}parallel NetCDF library located at${reset}: "$CDFDIR
 fi
 if [ -z $ADI ]; then
     ADIDIR=$(which adios_config)
     if [ -z $ADIDIR ]; then
-	echo "> without ADIOS library"
+	echo "> ${bold}without ADIOS library${reset}"
     else
 	ADIDIR=${ADIDIR%/*/*}
 	ADIOS=1
@@ -146,103 +155,149 @@ else
     ADIOS=1
 fi
 if [ $ADIOS -eq 1 ]; then
-    echo "> ADIOS library located at: "$CDFDIR
+    echo "> ${bold}ADIOS library located at${reset}: "$CDFDIR
 fi
 if [ $INTERACTIVE -eq 1 ]; then
-    echo "> an interactive interface"
+    echo "> ${bold}an interactive interface${reset}"
 else
-    echo "> the namelist interface"
+    echo "> ${bold}the namelist interface${reset}"
 fi
 
 # Check the compiler version to set the proper flags
 FCCOMPILER=($(mpif90 -show | tr ' ' ' '))
 FCCOMPILER=${FCCOMPILER[0]}
-if [ $FCCOMPILER = "gfortran" ]; then
-    FFLAGS="-O3 -fbacktrace -g -ffree-line-length-0"
-    CPPFLAGS="-x f95-cpp-input"
+if [ -z $BGCOMPILER ]; then
+    if [ $FCCOMPILER = "gfortran" ]; then
+	FFLAGS="-O3 -fbacktrace -g -ffree-line-length-0"
+	CPPFLAGS="-x f95-cpp-input"
+	MODFLAGS="-J\$(BINDIR)"
+    fi
+    if [ $FCCOMPILER = "ifort" ]; then
+	FFLAGS="-O3 -traceback -g"
+	CPPFLAGS="-fpp"
+	MODFLAGS="-module \$(BINDIR)"
+    fi
+    if [[ $FCCOMPILER = "pfg90" || $FCCOMPILER = "pgfortran" ]]; then
+	FFLAGS="-mp -03 -traceback -g"
+	CPPFLAGS="-Mpreprocess"
+	MODFLAGS="-module \$(BINDIR)"
+    fi
+    CPPFLAGS=$CPPFLAGS" -DINTERACTIVE=\$(INTERACTIVE) -DPOSIX=\$(POSIX) -DPOTOK=\$(POTOK) -DPNCDF=\$(PNCDF) -DPHDF5=\$(PHDF5) -DADIOS=\$(ADIOS) -DMPIIO=\$(MPIIO)"
+else
+    echo "> ${bold}Compilation on BlueGene${reset}"
+    FCCOMPILER=mpixlf90_r
+    FFLAGS="-qnullterm -O3 -g"
+    CPPFLAGS="-qsuffix=cpp=f90"
+    MODFLAGS="-qmoddir \$(BINDIR)"
+    PHYFLAGS="-WF,-DINTERACTIVE=\$(INTERACTIVE),-DPOSIX=\$(POSIX),-DPOTOK=\$(POTOK),-DPNCDF=\$(PNCDF),-DPHDF5=\$(PHDF5),-DADIOS=\$(ADIOS),-DMPIIO=\$(MPIIO),-DBLUEGENE=1"
+    KNOWNFC=1
 fi
-if [ $FCCOMPILER = "ifort" ]; then
-    FFLAGS="-O3 -traceback -g"
-    CPPFLAGS="-fpp"
-fi
-CPPFLAGS=$CPPFLAGS" -DINTERACTIVE=\$(INTERACTIVE) -DPOSIX=\$(POSIX) -DPOTOK=\$(POTOK) -DPNCDF=\$(PNCDF) -DPHDF5=\$(PHDF5) -DADIOS=\$(ADIOS) -DMPIIO=\$(MPIIO)"
 
 # Write the Makefile
 cat > Makefile <<EOF
+#===============================================================================
+# This Makefile was automatically generated by ./configure
+#===============================================================================
+# Echo variables for fancy outputs
+#===============================================================================
+bold  = \$(shell tput bold)
+reset = \$(shell tput sgr0)
+
+# Preprocessor variables
+#===============================================================================
 INTERACTIVE=${INTERACTIVE}
-POSIX=${POSIX}
-POTOK=${POTOK}
-PNCDF=${PNCDF}
-PHDF5=${PHDF5}
-ADIOS=${ADIOS}
-MPIIO=${MPIIO}
+POSIX = ${POSIX}
+POTOK = ${POTOK}
+PNCDF = ${PNCDF}
+PHDF5 = ${PHDF5}
+ADIOS = ${ADIOS}
+MPIIO = ${MPIIO}
 
-F90      = mpif90
-FFLAGS   = ${FFLAGS}
-CPPFLAGS = ${CPPFLAGS} 
-HDFINC   = -I${HDFDIR}/include/
-HDFLIB   = -L${HDFDIR}/lib -lhdf5_fortran -lhdf5 -lz
-CDFINC   = -I${CDFDIR}/include/
-CDFLIB   = -L${CDFDIR}/lib -lpnetcdf
+# Compiler and flags
+#===============================================================================
+F90       = mpif90
+FFLAGS    = ${FFLAGS}
+CPPFLAGS  = ${CPPFLAGS} 
+MODFLAGS  = ${MODFLAGS}
+HDFINC    = -I${HDFDIR}/include/
+HDFLIB    = -L${HDFDIR}/lib -lhdf5_fortran -lhdf5 -lz
+CDFINC    = -I${CDFDIR}/include/
+CDFLIB    = -L${CDFDIR}/lib -lpnetcdf
 ifeq (\$(ADIOS),1)
-ADIOSDIR = ${ADIDIR}
-ADIOSINC = \$(shell \${ADIOSDIR}/bin/adios_config -c -f)
-ADIOSLIB = \$(shell \${ADIOSDIR}/bin/adios_config -l -f)
+ADIOSDIR  = ${ADIDIR}
+ADIOSINC  = \$(shell \${ADIOSDIR}/bin/adios_config -c -f)
+ADIOSLIB  = \$(shell \${ADIOSDIR}/bin/adios_config -l -f)
 endif
+LIBFLAGS  = \$(HDFINC) \$(CDFINC) \$(ADIOSINC) \$(MPIINC)
+FLAGS     = \$(FFLAGS) \$(PHYFLAGS)
+ALLFLAGS  = \$(LIBFLAGS) \$(CPPFLAGS) \$(FLAGS)
+MAINFLAGS = \$(ALLFLAGS) -I\$(BINDIR) 
+ALLLIBS   = \$(HDFLIB) \$(CDFLIB) \$(MPILIB) \$(ADIOSLIB)
 
-VPATH  = src:src/modules
-SRCOBJ = \$(wildcard src/modules/*f90)
-MODOBJ = \$(SRCOBJ:.f90=.o)
-BRIOBJ = BRIO.o
-ALLOBJ = \$(MODOBJ) \$(BRIOBJ)
+# Sources, modules and binaries directories
+#===============================================================================
+SRCDIR   = src
+MODDIR   = \$(SRCDIR)/modules
+BINDIR   = bin
+BINDIRSC = ../\$(BINDIR)
+BINDIRMD = ../../\$(BINDIR)
+VPATH    = \$(SRCDIR):\$(MODDIR)
+MODSRC   = \$(wildcard \$(MODDIR)/*f90)
+MODOBJ   = \$(join \$(addsuffix \$(BINDIRMD)/, \$(dir \$(MODSRC))), \$(notdir \$(MODSRC:.f90=.o)))
+MAINSRC  = \$(wildcard \$(SRCDIR)/*f90)
+MAINOBJ  = \$(join \$(addsuffix \$(BINDIRSC)/, \$(dir \$(MAINSRC))), \$(notdir \$(MAINSRC:.f90=.o)))
+ALLOBJ   = \$(MODOBJ) \$(MAINOBJ)
 
 #============================================================================
 all: BRIO
-$(echo -e "\t")@echo "======================== BRIO =========================="
+$(echo -e "\t")@echo "======================== \$(bold)BRIO\$(reset) =========================="
 $(echo -e "\t")@echo "============= Benchmark for parallel I/O ==============="
 $(echo -e "\t")@echo "========================================================"
 $(echo -e "\t")@echo "With: "
 ifeq (\$(POSIX),1)
-$(echo -e "\t")@echo " - Sequential POSIX I/O"
+$(echo -e "\t")@echo " - \$(bold)Sequential POSIX I/O\$(reset)"
 endif
 ifeq (\$(POTOK),1)
-$(echo -e "\t")@echo " - Sequential POSIX I/O with token management"
+$(echo -e "\t")@echo " - \$(bold)Sequential POSIX I/O with token management\$(reset)"
 endif
 ifeq (\$(PNCDF),1)
-$(echo -e "\t")@echo " - Parallel NetCDF I/O"
+$(echo -e "\t")@echo " - \$(bold)Parallel NetCDF I/O\$(reset)"
 endif
 ifeq (\$(PHDF5),1)
-$(echo -e "\t")@echo " - Parallel HDF5 I/O"
+$(echo -e "\t")@echo " - \$(bold)Parallel HDF5 I/O\$(reset)"
 endif
 ifeq (\$(ADIOS),1)
-$(echo -e "\t")@echo " - Adaptive I/O System"
+$(echo -e "\t")@echo " - \$(bold)Adaptive I/O System\$(reset)"
 endif
 ifeq (\$(MPIIO),1)
-$(echo -e "\t")@echo " - MPI-IO"
+$(echo -e "\t")@echo " - \$(bold)MPI-IO\$(reset)"
 endif
 $(echo -e "\t")@echo "========================================================"
-$(echo -e "\t")@echo " > compilation successful!"
-#============================================================================
-%.o:%.f90
-$(echo -e "\t")@echo " > Compiling object: "\$@
-$(echo -e "\t")\$(F90) \$(HDFINC) \$(CDFINC) \$(ADIOSINC) \$(FLAGS) \$(MPIINC) \$(CPPFLAGS) -c \$^ -o \$@
+$(echo -e "\t")@echo " > \$(bold)compilation successful!\$(reset)"
+#== Modules ==================================================================
+\$(MODDIR)/\$(BINDIRMD)/%.o: %.f90
+$(echo -e "\t")@echo "> \$(bold)Compiling modules\$(reset): "\$@
+$(echo -e "\t")\$(F90) \$(ALLFLAGS) -c \$^ -o \$@ \$(MODFLAGS)
+#== Main sources ===============================================================
+\$(SRCDIR)/\$(BINDIRSC)/%.o: %.f90
+$(echo -e "\t")@echo "> \$(bold)Compiling main sources...\$(reset)"
+$(echo -e "\t")\$(F90) \$(MAINFLAGS) -c $^ -o \$@
 #============================================================================
 BRIO: adios \$(ALLOBJ)
-$(echo -e "\t")@echo " > Compiling BRIO..."
-$(echo -e "\t")\$(F90) \$(FLAGS) -o ./BRIO \$(ALLOBJ) \$(HDFLIB) \$(CDFLIB) \$(MPILIB) \$(ADIOSLIB)
-$(echo -e "\t")mv *o *mod BRIO bin/
+$(echo -e "\t")@echo " > \$(bold)Compiling BRIO...\$(reset)"
+$(echo -e "\t")\$(F90) \$(FLAGS) -o ./bin/BRIO \$(ALLOBJ) \$(ALLLIBS)
 #============================================================================
 ifeq (\$(ADIOS),1)
 adios:
-$(echo -e "\t")@echo " > Generating *.fh files..."
+$(echo -e "\t")@echo " > \$(bold)Generating *.fh files...\$(reset)"
 $(echo -e "\t")gpp.py input/adios_BRIO.xml
-$(echo -e "\t")mv *fh src/modules/
+$(echo -e "\t")mv *fh \$(MODDIR)
 else
 adios:
 endif
 #============================================================================
 clean:
-$(echo -e "\t")@echo " > Cleaning sources and binaries directories..."
-$(echo -e "\t")rm -rf bin/*.o src/modules/*.o src/modules/*.fh bin/*.mod input/*.h5 input/*.nc input/*.bp input/*.mp input/sequentialio/
+$(echo -e "\t")@echo " > \$(bold)Cleaning sources and binaries directories...\$(reset)"
+$(echo -e "\t")rm -rf \$(BINDIR)/*.o \$(BINDIR)/*.mod \$(MODDIR)/*.fh input/*.h5 input/*.nc input/*.bp input/*.mp input/sequentialio/
 
 EOF
